% phdisabled, migraines

# Being a PhD Student and PostDoc with Migraines

A blog post on the [Weecology group blog](http://jabberwocky.weecology.org/2014/10/13/how-technology-can-help-scientists-with-chronic-illnesses-or-technology-ftw/) by [Elita Baldridge](https://twitter.com/elitabaldridge) on being a PhD student with fibromyalgia, and how they are working through that, caused me to pause and reflect on my experience as a PhD and PostDoc with migraines.

## Migraine

For those who don't know, migraines are a rather unusual neurological event that result in a bunch of symptoms, the most well known generally being aura (frequently visual, although auditory and olfactory are also known) followed by what is described as intense, debilitating pain, which may or may not be accompanied by extreme nauseau and / or vomiting and tiredness.

## My Migraines

I have suffered from migraines since at least my early teens (possibly younger), but mine seem to be rather mild in comparison to what I have read about others experiences. In contrast to many other migraineurs, I do not experience visual aura, and in general my pain levels tend to be on the milder side. However, I do experience mood swings during my prodrome (period prior to pain), going from a generally nice guy to someone who considers killing you just for looking at me wrong; I also experience [expressive aphasia](http://en.wikipedia.org/wiki/Aphasia), wherein I can no longer remember proper nouns, but can describe properties of the object in question (for example, instead of a pencil, I might say the writing implement with lead). In addition to the pain of the migraine, which is often a pounding localized to one location of my skull, I often also experience extreme sensitivity to touch, to the point of not being able to sleep on a few occasions.

As far as I can tell, my primary migraine trigger is changes in the weather, either from nice to nasty, or even in the other direction. If the weather is stable (either nice or bad), the frequency and severity of my migraines are greatly reduced.

## PhD

During my undergraduate and masters degrees, I actually didnt notice that !uch of an effect from my migraines. At some ppint, after a lpt of investigation of my headaches, and alternative therapies, I did finally get a diagnosis of migraine, and a prescription for Maxalt, a triptan used to treat migraines. I used this very sparingly, due to the side effects, and the cost.

My PhD was at Dalhousie University in Halifax, NS, Canada. If you dont know, Halifax is a harbor city on the east coast of Nova Scotia, and as a result of its location has very variable weather, as it get the west -> east weather from the rest of Canada, as well as weather systems going south -> north up the eastern seaboard of the United States. This results in a large amount of barometric pressure changes, and resulted in a lot of migraines for me. In general, my solution when possible was to go home, take 2 tylenol, and go to bed for the rest of the day. As a PhD student in an analytical chemistry lab doing no wet lab work but only programming, this was often a viable option. My PhD supervisor was very supportive, in that as long as grades were good and project progress was being made, he was not particular about hours spent in the lab

oOf course, as a PhD student, there were times this was not possible. I took classes in my first 2 years, and I never informed any of my instructors about my migraines, but often just suffered through classes if necessary. In addition, I TA'd first and second year chmeistry lab. Given the other synptoms of my migraines, I actually feel sorry for the students I instructed. I know many times I had trouble resolving what were probably trivial mistakes by first year students, and losing my coolover something that was not that difficult to fix. Second year was a bit better in that the students had more experience in a lab setting, however I TA'd analytical chemistry, which essentially involved generating a series of standards, measuring the standards, and then measuring a sample with unknown concentration. There was generally fewer ways for any given lab experiment to fail in the 2nd year lab, putting a lighter cognitive load on me most days.

## Seminars and Conferences

Of course, as a student I had to attend weekly departmental seminars, and present a couple of times as well. I also traveled to a few conferences and presented talks and posters. To my recollection, I have not suffered a severe migraine during my own talks at a conference. However, I have had different occasions where I have had to skip out on conference sessions due to a migraine, and have been even less likely to socialize and network than I usually would because of migraines. This is hard, because one of the primary purposes of attending conferences is exposure to new research and people.